default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ajax_app_rails7_development

test:
  <<: *default
  database: ajax_app_rails7_test

production:
  <<: *default
  database: ajax_app_rails7_production
  username: ajax_app_rails7
  password: <%= ENV['AJAX_APP_RAILS7_DATABASE_PASSWORD'] %>
