default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima-39497_development

test:
  <<: *default
  database: furima-39497_test

production:
  <<: *default
  database: furima-39497_production
  username: furima-39497
  password: <%= ENV['FURIMA_39497_DATABASE_PASSWORD'] %>
